# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

certified_hotels = Certified_hotels.create([
    { name: 'Hilton Vancouver Conference Center & Hotel - Vancouver, WA',
    hotel_id: '227029',
    certification: 'LEED'},
    { name: 'W Hollywood Hotel & Residences - LA, CA',
    hotel_id: '335297',
    certification: 'LEED'},
    { name: 'Orchard Garden Hotel - San Francisco, CA',
    hotel_id: '248276',
    certification: 'LEED'},
    { name: 'Westin Riverfront Resort & Spa - Avon, CO',
    hotel_id: '265697',
    certification: 'LEED'},
    { name: 'Orchard Hotel - San Francisco, CA',
    hotel_id: '192358',
    certification: 'LEED'},
    { name: 'Cavallo Point Lodge - San Francisco, CA',
    hotel_id: '265998',
    certification: 'LEED'},
    { name: 'Portola Hotel & Spa Monterey - Monterey, CA',
    hotel_id: '111950',
    certification: 'LEED'},
    { name: 'Element Westin - Houston, TX',
    hotel_id: '307809',
    certification: 'LEED'},
    { name: 'Venetian Resort - Las Vegas, NV',
    hotel_id: '147594',
    certification: 'LEED'},
    { name: 'Mandarin Oriental - Las Vegas, NV',
    hotel_id: '332841',
    certification: 'LEED'},
    { name: 'Fairmont Pittsburgh - Pittsburgh, PA',
    hotel_id: '338425',
    certification: 'LEED'},
    { name: 'Four Points - Tallahassee, FL',
    hotel_id: '137719',
    certification: 'LEED'},
    { name: 'Caribe Royal - Orlando, FL',
    hotel_id: '116827',
    certification: 'The Code'},
    { name: 'Hotel Carlton, San Francisco, CA',
    hotel_id: '120750',
    certification: 'LEED'},
    { name: 'Hotel de la Opera - Bogota, Columbia',
    hotel_id: '240824',
    certification: 'The Code'},
    { name: 'Hampton Inn and Suites Sarasota Airport',
    hotel_id: '326410/',
    certification: 'LEED'},
    { name: 'Palomar-Klimpton Philadelphia, PA',
    hotel_id: '326836',
    certification: 'LEED'},
    { name: 'Fairfield Inn and Suites- Baltimore Downtown, MD ',
    hotel_id: '313621',
    certification: 'LEED'},
    { name: 'Hotel Indigo - Gaslamp, San Diego, CA',
    hotel_id: '324243',
    certification: 'LEED'},
    { name: 'ITC Maurya - New Delhi, India',
    hotel_id: '105818',
    certification: 'LEED'},
    { name: 'ITC The Mughal - Agra, India',
    hotel_id: '105817',
    certification: 'LEED'},
    { name: 'ITC Maratha - Mumbai, India',
    hotel_id: '193552',
    certification: 'LEED'},
    { name: 'ITC Grand Central - Mumbai, India',
    hotel_id: '224860',
    certification: 'LEED'},
    { name: 'ITC Sonar - Kolkata, India',
    hotel_id: '215054',
    certification: 'LEED'},
    { name: 'ITC Windson - Bengaluru, India',
    hotel_id: '105869',
    certification: 'LEED'},
    { name: 'Alila Villas Uluwatu - Bali, Indonesia',
    hotel_id: '308154',
    certification: 'EarthCheck'},

    ])

destinations = Destination.create([
 { name: 'The Victorian',
    location: 'Plainfield, CT',
    website: 'http://i.imgur.com/jycojI8.jpg',
    certification: 'Hires Inclusively, Staff Development',
    category: 'Restaurant: Breakfast & Lunch',
    desc_prod: 'The Victorian, located in the Northeastern quadrant of Connecticut, serves traditional New England breakfast and lunch Monday through Friday. All menu items including the breads, pies and other assorted sweets goods are baked up daily on-site. Guests are welcome to enjoy their meals and wander around the property which boasts a greenhouse bearing both flowers and vegetables. All of the baked goods can also be bought out of the bakery case or wholesale to be sold at farm stands throughout the area. The Victorian’s fruit pies are renowned in the region for their classic excellence with all fruit sourced locally.',
    desc_good: ' In the early 1980’s Connecticut’s Legislature voted to close down state institutions, which housed individuals with intellectual and developmental disabilities. At that point all residents of the institutions were returned to their hometowns and required to seek services privately. Out of this need Seabird Enterprises was established as a private 501(c)3 nonprofit dedicated to providing vocational training to people with developmental disabilities. Seabird Enterprises owns and operates The Victorian as part of their vocational training program.
Trainees learn all aspects of working in a restaurant from wait staff skills to baking and food preparation. Much of the training replicates the processes of the local chain restaurants, which typically hire trainees upon completion of their time with Seabird. These skills can be used as a step toward independent employment, while others make a career of the program. Trainees in the restaurant are paid through the program. Wages are based on average productivity and hours worked. These wages typically are offset by entitlements individuals receive from the Social Security Administration. Staff pay and benefits are among the best within the industry.',
    directions: 'Located off of Route 12 in Plainfield, CT. (860) 564-2505',
    recommended: 'Made fresh-daily fruit pies!', 
    seo_tags: 'Connecticut, Locally Made, Baked Goods, Job Training'},

  { name: 'Akha Ama',
    location: 'Chiang Mai, Thailand',
    website: 'www.akhaama.com/',
    certification: 'Cooperative, Regional Sourcing, Hires Inclusively',
    category: 'Coffee Shop',
    desc_prod: ' Finding great coffee on the road is often a sore spot for the adventurous and well-intentioned traveler but in Akha Ama one finds respite. The trendy little cafe is home to an award-winning Barista, fair-trade cuppas, pastries, tea and juice. The beans, grown and processed locally, were selected by the Specialty Coffee Association of Europe for the World Cup Tasters Championship in 2010, 2011 and 2012. In 2013, the accolades kept coming when Barista Jenny won first place for espresso wizardry in a Northern Thailand competition. A superb cup of coffee will run you 45 Thai Baht a cup (~$1.50 USD), and if you love it as much as we think you will you can grab a bag of beans to share back home.',
    desc_good: 'You’d never know that Mr. Lee Ayu, an Akha man, may have started a kind of revolution in thinking among hill tribe people; or at least in his own village and the 14 families who now comprise Akha Ama growers. Ayu learned about community development at University and about how his people were constantly at the mercy of both the weather and middle-men.
The Akha are an indigenous hill tribe people living in small, high altitude villages in the mountains of Burma, China, Laos, Thailand and Vietnam. They are an ethnic minority in all of these nations, so you can guess what that means: marginalization, poverty and discrimination.
Coffee is the second most widely traded commodity globally. But the beans have a narrow window of time between harvest and processing before they go bad. That narrow window gives 3rd-party processors leverage for low-balling local growers out of their hard-earned harvests. Thus, by guiding his kinfolk, already 15+ years in the bean-growing business, into bean processing Ayu has managed to outwit erstwhile predatory bean buyers.
Once the village growers followed Lee’s advice and invested in learning how to process their own beans, they could afford to wait for a better bid. The results? Higher quality coffee for the end consumer and a higher quality life for the growers.',
    directions: 'Akha Ama Coffee 9/1 Mata Apartment, Soi 3, Hussadhisewee Road, Chiang Mai. Tel.: 66-86-915-8600',
    recommended: 'The Shakerato',
    seo_tags: 'Coffee, Coop, Locally Sourced'},

  { name: 'Snowday',
    location: 'New York, New York',
    website: 'http://drivechangenyc.org/',
    certification: 'Hires Inclusively, Staff Development, ',
    category: 'Food Truck',
    desc_prod: 'Those who were raised in the Northeast will remember the joy of a school snowday. A day without worries and lots of treats, preferably maple syrup topped ones. Thus the concept for Snowday, a maple themed food truck with adult sophistication, was born. The Farm to Truck social enterprise sources 100% of its ingredients from area farms and small businesses to keep it local and fresh. The menu boasts an impressive array of sandwiches and salads curated by Culinary Arts Director, Jared Spafford (and the rest of the team). The house specialty is “maple grilled cheese”– fresh-daily baked sour dough bread with extra sharp cheddar cheese topped off with Grade B New York State maple syrup. A nostalgic lunch will set you back $10, tops, plus a couple bucks for Sugar on Snow, hot maple syrup over fresh shaved ‘snow’.',
    desc_good: ' Drive Change founder Jordyn Lexton launched the social enterprise to hire, teach and empower formerly incarcerated youth. Lexton taught English for three years on Riker’s Island in New York City to incarcerated young men, ages 16-18 years old and is well versed in the issues facing youth upon re-entry.  Riker’s Island on the East River in the Bronx is New York City’s largest jail complex. It houses over 12,000 inmates; 8% of whom are minors. New York is one of two states in the US that automatically treats 16 year-olds as adults at the point of arrest. It is a remnant of an archaic law passed in 1964 under the pretense of being temporary. As a result, these minors are incarcerated and receive felonies on their records versus juvenile adjudications, which severely limits their ability to find quality work upon release. The trend contributes to a nearly 70% recidivism rate, or a return to the criminal justice system. In 2013, the cost to house an inmate on Riker’s Island to the City of New York was $167,000 annually.
Drive Change works with individuals aged 16-25 all of whom have had direct impact with the adult criminal justice system. Drive Change aims to bring the recidivism rate down to 20% and so far all the employees on a bright path. The 8-person crew members are paid weekly at almost 40% over minimum wage in New York. They also receive continuing education and training on money management, culinary arts, hospitality, business development, entrepreneurship training, social media, food sustainability and criminal justice advocacy. The program is transitional; it is 6-8 months long and rotates three times a year allowing each truck to train up to 30 young people per year.',
    directions: 'Snowday comes to you! Follow @drivechangenyc and @snowdaytruck on Twitter ',
    recommended: 'The Famous Maple Grilled Cheese',
    seo_tags: 'Connecticut, Locally Made, Baked Goods, Job Training'}

    ])

